services:
  twilio:
    image: bernylinville/call-alert-by-twilio
    container_name: call-alert-by-twilio
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_CALL_TO
      - TWILIO_CALL_FROM
      - WEB_PORT=11337
    ports:
      - "11337:11337"
